// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const PHONE_ENABLE_LOADER = 'PHONE_ENABLE_LOADER';
export const PHONE_DISABLE_LOADER = 'PHONE_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// phone
export const PHONE_REQUEST = 'PHONE_REQUEST';
export const PHONE_RESPONSE = 'PHONE_RESPONSE';
export const PHONE_LOADING_ENDED = 'PHONE_LOADING_ENDED';
export const PHONE_FAILED = 'PHONE_FAILED';
export const PHONE_RESET = 'PHONE_RESET';
